version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: dev-pg
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-ddns}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changemedev}
      POSTGRES_DB: ${DB_NAME:-ddns_dev}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nikoder.dev
      PGADMIN_DEFAULT_PASSWORD: changemedev
    networks:
      - backend

networks:
  backend:
